apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLakNDQWhLZ0F3SUJBZ0lRVG5GVDR2YWNhZStGRjR4aTgvMFI0REFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlRMU1ESTBNR1UwT1MxaVlXVmlMVFJsTVRVdE9HTXpOUzAxTW1VNFptUTJZVEppTmpRdwpIaGNOTWpBeE1UQTVNVE14TmpNMFdoY05NalV4TVRBNE1UUXhOak0wV2pBdk1TMHdLd1lEVlFRREV5UTFNREkwCk1HVTBPUzFpWVdWaUxUUmxNVFV0T0dNek5TMDFNbVU0Wm1RMllUSmlOalF3Z2dFaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURxNDFvUXQzeEh3VjAxRFVaSlVrb0xrTWlFeWQ1RHR0VWIyOG1ZRXB1YwpkOFAyOVM0cTlEcnpFb3VkOFNaOGI2QzdoREVJbFkvNERMU1NxVFMyR01CMGJDdUxOeDd2OG9wY3p0NkFDVDBFCm9yZXBkaStVbm1sV0NBcS96K2pOaXBZS0dzeWNKa2k4UEdSTnR3OG0zV1FGNlhJZVNZdFNRbjBSL0l4bUdyazcKS1djeVc1UG5jaExUNXpaN0lFaFI4cVE0K0JybmZPdTBuWEN1dkxQTHNvT0l0N3c3TFpXSVk3U3RBUHV0TUxYMQpRcmFCTHRyQlRNSzFJeGY1RVBUaWphaEhzZE0xOU9OYVN3M0UvWDg5cEoxb1VUSHdEdE5Bb2tMNFVuS0VwRi9DCmhlRElMdTIzZDgwVTJyVVFScDlReDE0bGRkeDJ3V2xKNCtZblBTdXZWenBYQWdNQkFBR2pRakJBTUE0R0ExVWQKRHdFQi93UUVBd0lDQkRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSVnZqdW9tdExYYXRhNApJTHdhTTlSaXhqYS96ekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBbWoyMUFJRVkxODQ2YTJRSnRlVGxtT2R5CkFqM0EwR0Jvd016bzVqbU5kdkswY0pJNTVYOFQ0Nm4zOUE2SEQxaUpYQ3BBOExxNUpabnJ3NmRpQ0VLMCtQK2MKUCthYWlIMVEvSm5NM2pXOWlML0dqc0FrOTFWZm5JYVNKc0tjYVBtN1hkQWZHdXFMVXRIdStkUGRQRGd6dHFkRwpKVWpRNFIrVXl4bldwR1BDWTVISzFoN0tBS0p0UDJYUFJUWTJ2NkFuQnVGam9JZGVmYVR2Ym42bndBTTIraXJqCmw1UjkzYjcvcm9sZU52QU02RFlpTThHd1RHZHN3WmQ5REI0SjN5VnpNTExmYVE3MmRBUk1sWTdhZGVZaUtvdTcKYzI0TW9VZ2xyUlNGY3pRbktHWXFXMys4WC9zMWRaSDd4VkNJMlc1ODVmaHhZVjlNUHJHS2FzQnRZSUd5NVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://35.228.38.252
  name: gke_andrelin-dev_europe-north1-a_demo-cluster
contexts:
- context:
    cluster: gke_andrelin-dev_europe-north1-a_demo-cluster
    namespace: default
    user: gke_andrelin-dev_europe-north1-a_demo-cluster
  name: demo-cluster
current-context: demo-cluster
kind: Config
preferences: {}
users:
- name: gke_andrelin-dev_europe-north1-a_demo-cluster
  user:
    auth-provider:
      config:
        access-token: ya29.A0AfH6SMDFxqCwUkX5hvrcfPOerPWy_E2CyArdRDIbDtIZpncPNgzsRFZoFVvjVywjKlZ12LPjYyT38e93QS2ZwIPjIPEN6h1hpZ_zxNGEfyNGNMylDO-l9iUaG1ZEXxM2O7sVMpcewg46o6HS_Yo4_g21SpZmMeZRDAdzWkZQT2h3N073rce3vZsCpSinWRjDf04
        cmd-args: config config-helper --format=json
        cmd-path: /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/gcloud
        expiry: "2020-11-10T16:55:36Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
